### ISSUE TITLE
Adding operations to ocs agents will crash the registry

### ISSUE THREAD

**Issue by jlashner** [simonsobs/ocs#254] opened 2022-02-01 22:51 UTC
This will be very rare during operation, but when additional operations are added to an ocs agent it breaks the block structure of the registry's OCS feed and crashes the main process. Just saw this error at UCSD when Max was working on developing a new agent:

```
ocs-registry_1             | 2022-02-01T22:26:40+0000 main:0 CRASH: [Failure instance: Traceback: <class 'Exception'>: Block structure does not match: observatory.labjack-beammap
ocs-registry_1             | /usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:662:callback
ocs-registry_1             | /usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:764:_startRunCallbacks
ocs-registry_1             | /usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:858:_runCallbacks
ocs-registry_1             | /usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:1751:gotResult
ocs-registry_1             | --- <exception caught here> ---
ocs-registry_1             | /usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:1661:_inlineCallbacks
ocs-registry_1             | registry.py:175:main
ocs-registry_1             | /usr/local/lib/python3.8/dist-packages/ocs/ocs_agent.py:512:publish_to_feed
ocs-registry_1             | /usr/local/lib/python3.8/dist-packages/ocs/ocs_feed.py:221:publish_message
ocs-registry_1             | /usr/local/lib/python3.8/dist-packages/ocs/ocs_feed.py:35:append
ocs-registry_1             | ]
```

**Comment by BrianJKoopman** [comment] 2022-12-17 02:28
#311 was opened as a duplicate of this, but it has a better traceback. Going to close this one as duplicate, consider it superseded by #311.

**Closed by BrianJKoopman** 2022-12-17 02:28 UTC
Labels: bug
